"""
sync_config1_boxes.py
----------------------
Root cause, confirmed by direct testing (2026-09-10): in this Langflow
install, a CustomComponent field's value (DropdownInput, MessageTextInput,
whatever) is NEVER honored at actual run time, no matter how it was set -
typed in the UI, or written into the flow's saved JSON via the API. Proven
three separate ways: with real_time_refresh on, with it off, and on a
completely fresh node id that had never been touched before - all three
returned self.saved_config = None at execution, despite the flow's saved
JSON correctly holding "demo_test1". Only ONE mechanism reliably delivers
a value into a running component here: a literal Python constant baked
directly into that component's own source code, returned from a method,
carried across a WIRE to the next node. That is exactly how the ORIGINAL
"LandIQ Config: <name>" boxes worked before any of today's dropdown
attempts - CONFIG_NAME as a plain module-level string, zero input fields
for it, output via emit_model_config(). Confirmed working again just now
via the same targeted-build test.

So a single live dropdown whose selection actually matters is not
achievable as a plain field in this Langflow version - full stop. This
script gets as close as technically possible to what was asked for while
staying on the one mechanism that is proven to work:

  - One small, real box per ACTIVE config on the LandIQ website, each
    with that config's name baked in as its own literal constant (so its
    output is 100% guaranteed to reach whatever it's wired into).
  - The set of boxes is kept in sync with the REAL, LIVE list from
    GET /configs/active every time this script runs - add a box for a
    brand-new client config, remove one for a deleted config. Nothing
    about WHICH configs exist is hardcoded; only the delivery mechanism
    (a wire, not a dropdown) is fixed, because that's what this Langflow
    install actually supports reliably.
  - Whichever box was already feeding "LandIQ Config Agent" keeps feeding
    it (no change to current behavior). To use a different config, wire a
    different box in - a few seconds' drag on the canvas, and (unlike a
    dropdown here) guaranteed to actually work when you run it.

Usage:
    python sync_config1_boxes.py
"""

import datetime
import gzip
import json
import pathlib
import sys
import urllib.request
import urllib.error

LANGFLOW = "http://127.0.0.1:7860"
BACKEND = "http://127.0.0.1:8000"
ROOT = pathlib.Path(__file__).resolve().parent
FLOW_ID_FILE = ROOT / "langflow_flow_id.txt"
API_KEY_FILE = ROOT / "langflow_api_key.txt"
CONFIG_AGENT_ID = "CustomComponent-ConfigAgent"
BROKEN_DROPDOWN_ID = "CustomComponent-ConfigPicker"


def die(msg):
    print("\n[X] " + msg + "\n")
    sys.exit(1)


def api_key():
    return API_KEY_FILE.read_text(encoding="utf-8").strip() if API_KEY_FILE.exists() else ""


def call(method, path, body=None, timeout=30, base=LANGFLOW):
    url = base + path
    data = json.dumps(body).encode("utf-8") if body is not None else None
    headers = {"Content-Type": "application/json", "Accept-Encoding": "identity"}
    key = api_key()
    if key:
        headers["x-api-key"] = key
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            raw = r.read(); status_code = r.status
    except urllib.error.HTTPError as e:
        raw = e.read(); status_code = e.code
    if raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    try:
        return status_code, json.loads(raw.decode("utf-8"))
    except json.JSONDecodeError:
        return status_code, {"error": raw.decode("utf-8", "replace")[:2000]}


def handle_str(d):
    return json.dumps(d, separators=(",", ":")).replace('"', "œ")


def make_edge(source_id, source_handle, target_id, target_handle):
    eid = "xy-edge__%s%s-%s%s" % (source_id, handle_str(source_handle), target_id, handle_str(target_handle))
    return {
        "source": source_id, "sourceHandle": handle_str(source_handle),
        "target": target_id, "targetHandle": handle_str(target_handle),
        "data": {"targetHandle": target_handle, "sourceHandle": source_handle},
        "id": eid, "animated": False, "className": "", "selected": False,
    }


COMPONENT_TEMPLATE = '''"""
LandIQ Config: {config_name} - Config 1 box.

Proven-reliable pattern only: CONFIG_NAME is a plain Python constant baked
directly into this file (not a field, not a dropdown) - confirmed by
direct testing that this is the ONLY mechanism that actually delivers a
value to a running component in this Langflow install. Wire this box's
output into "LandIQ Config Agent" to run agents against '{config_name}'.
Regenerated by sync_config1_boxes.py from the live LandIQ website config
list - to pick up a brand-new config, or drop one that was deleted,
re-run that script; nothing here is hand-maintained.
"""

from lfx.custom.custom_component.component import Component
from lfx.io import MessageTextInput, Output
from lfx.schema.data import Data

BACKEND_URL = "{backend_url}"
CONFIG_NAME = "{config_name}"


class LandIQConfigSource_{safe_name}(Component):
    display_name = "LandIQ Config: {config_name}"
    description = (
        "Config 1 - the real, active '{config_name}' LandIQ website config. "
        "Wire this box's output into 'LandIQ Config Agent' to run any agent "
        "against it. To use a different config, wire a different "
        "'LandIQ Config: ...' box in instead."
    )
    icon = "sparkles"
    name = "LandIQConfigSource_{safe_name}"

    inputs = [
        MessageTextInput(
            name="prompt",
            display_name="Test Prompt",
            value="Say hello and state your model name.",
            info="Sent on every run as a live proof-of-connection - check the Logs tab.",
        ),
    ]

    outputs = [
        Output(display_name="Model Config", name="model_config_out", method="emit_model_config"),
    ]

    def emit_model_config(self) -> Data:
        import httpx

        cfg = {{"mode": "saved", "config_full_name": CONFIG_NAME}}
        prompt = self.prompt or ""

        try:
            r = httpx.post(
                f"{{BACKEND_URL}}/test/{{CONFIG_NAME}}",
                json={{"prompt": prompt, "max_tokens": 512, "temperature": 0.3}},
                timeout=45,
            )
            data = r.json()
        except Exception as e:
            cfg["live_proof"] = f"[error] {{type(e).__name__}}: {{str(e)[:250]}}"
            self.status = cfg["live_proof"]
            return Data(data=cfg)

        if data.get("success"):
            cfg["live_proof"] = (
                f"LIVE, direct call to '{{CONFIG_NAME}}' -> {{data.get('response', '')}} "
                f"[served by {{data.get('model_used', '?')}}, tokens: {{data.get('total_tokens', '?')}}]"
            )
        else:
            cfg["live_proof"] = f"[error] Config '{{CONFIG_NAME}}' call failed: {{data}}"
        self.status = cfg["live_proof"]
        return Data(data=cfg)
'''


def safe_ident(name):
    return "".join(c if c.isalnum() else "_" for c in name)


print("\n[1/7] Reading the real, active config list from the LandIQ website ...")
cs, active = call("GET", "/configs/active", base=BACKEND)
if cs >= 400:
    die("Could not reach backend /configs/active (HTTP %s)" % cs)
live_names = [c["full_name"] for c in active if c.get("full_name")]
if not live_names:
    die("No active configs found on the website - create one first.")
print("      -> %d active config(s): %s" % (len(live_names), live_names))

print("\n[2/7] Loading the live flow ...")
if not FLOW_ID_FILE.exists():
    die("langflow_flow_id.txt not found.")
flow_id = FLOW_ID_FILE.read_text(encoding="utf-8").strip()
status, flow = call("GET", "/api/v1/flows/%s" % flow_id)
if status >= 400 or not flow.get("data"):
    die("Could not load flow %s (HTTP %s): %s" % (flow_id, status, flow))
nodes = flow["data"].get("nodes", [])
edges = flow["data"].get("edges", [])

print("\n[3/7] Backing up the live flow before changing anything ...")
ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
backup_path = ROOT / ("scratch_live_flow_backup_before_config1_wired_sync_%s.json" % ts)
backup_path.write_text(json.dumps(flow, indent=2, default=str), encoding="utf-8")
print("      -> backup saved: %s" % backup_path.name)

print("\n[4/7] Fetching the custom-component frontend template ...")
cstatus, cresult = call("GET", "/api/v1/all")
if cstatus >= 400:
    die("Could not fetch component registry (HTTP %s)" % cstatus)
custom_template = cresult["custom_component"]["CustomComponent"]


def build_source_box(config_name):
    code = COMPONENT_TEMPLATE.format(
        config_name=config_name, backend_url=BACKEND, safe_name=safe_ident(config_name)
    )
    vstatus, vresult = call("POST", "/api/v1/validate/code", {"code": code})
    if vstatus >= 400 or vresult.get("imports", {}).get("errors") or vresult.get("function", {}).get("errors"):
        die("Box for '%s' failed validation: %s" % (config_name, vresult))
    bstatus, bresult = call("POST", "/api/v1/custom_component",
                             {"code": code, "frontend_node": custom_template})
    if bstatus >= 400:
        die("Could not build box for '%s' (HTTP %s): %s" % (config_name, bstatus, bresult))
    return bresult["data"]


print("\n[5/7] Building one real box per active config ...")
existing_source_ids = {
    n["id"]: n for n in nodes
    if n.get("data", {}).get("type", "").startswith("LandIQConfigSource")
}
# Map by the config name embedded in the node id we use: CustomComponent-Source-<name>
desired_ids = {name: "CustomComponent-Source-%s" % safe_ident(name) for name in live_names}

kept_nodes = [n for n in nodes if n["id"] not in existing_source_ids and n["id"] != BROKEN_DROPDOWN_ID]
removed_stale = [nid for nid in existing_source_ids if nid not in desired_ids.values()]
removed_broken_dropdown = any(n.get("id") == BROKEN_DROPDOWN_ID for n in nodes)

# Reuse existing node positions where possible so the canvas doesn't jump around.
old_positions = {n["id"]: n["position"] for n in nodes if n["id"] in existing_source_ids}
fallback_pos = {"x": 3200, "y": 900}
i = 0
new_source_nodes = []
for name, node_id in desired_ids.items():
    pos = old_positions.get(node_id) or {"x": fallback_pos["x"] + (i % 4) * 340, "y": fallback_pos["y"] + (i // 4) * 260}
    i += 1
    node_data = build_source_box(name)
    new_source_nodes.append({
        "id": node_id, "type": "genericNode", "position": pos,
        "selected": False, "dragging": False, "measured": {"width": 320, "height": 254},
        "data": {"showNode": True, "type": "LandIQConfigSource_%s" % safe_ident(name),
                 "id": node_id, "selected_output": None, "node": node_data},
    })
    print("      -> box ready: LandIQ Config: %s (%s)" % (name, node_id))

print("      -> %d box(es) built, %d stale box(es) removed, broken dropdown removed: %s"
      % (len(new_source_nodes), len(removed_stale), removed_broken_dropdown))

new_nodes = kept_nodes + new_source_nodes

print("\n[6/7] Rewiring Config 1 -> Config 2 (keeping the same config already feeding it, if still active) ...")
prior_edge = next((e for e in edges if e.get("target") == CONFIG_AGENT_ID), None)
prior_source_id = prior_edge.get("source") if prior_edge else None
prior_name = None
for name, nid in desired_ids.items():
    if prior_source_id and (nid == prior_source_id or prior_source_id in existing_source_ids):
        # try to recover the config name from the old node's display name
        old_node = existing_source_ids.get(prior_source_id)
        if old_node:
            dn = old_node["data"]["node"].get("display_name", "")
            if dn.endswith(name):
                prior_name = name
                break

chosen_name = prior_name if prior_name in live_names else ("demo_test1" if "demo_test1" in live_names else live_names[0])
chosen_id = desired_ids[chosen_name]

new_edges = [e for e in edges if e.get("target") != CONFIG_AGENT_ID and e.get("source") not in existing_source_ids]
new_edges.append(make_edge(
    chosen_id,
    {"dataType": "LandIQConfigSource_%s" % safe_ident(chosen_name), "id": chosen_id,
     "name": "model_config_out", "output_types": ["Data"]},
    CONFIG_AGENT_ID,
    {"fieldName": "model_config", "id": CONFIG_AGENT_ID, "inputTypes": ["Data", "JSON"], "type": "other"},
))
print("      -> 'LandIQ Config Agent' now wired to: %s" % chosen_name)

print("\n[7/7] Saving to the live flow ...")
payload = {
    "name": flow.get("name", "LandIQ Orchestrator"),
    "description": flow.get("description", ""),
    "data": {"nodes": new_nodes, "edges": new_edges},
}
pstatus, presult = call("PATCH", "/api/v1/flows/%s" % flow_id, payload, timeout=60)
if pstatus >= 400:
    die("Langflow rejected the update (HTTP %s): %s\n\nBackup untouched at %s" % (pstatus, presult, backup_path.name))

vstatus2, vflow = call("GET", "/api/v1/flows/%s" % flow_id)
vnodes = vflow.get("data", {}).get("nodes", [])
vedges = vflow.get("data", {}).get("edges", [])
print("\n" + "=" * 66)
print("  DONE")
print("=" * 66)
print("  Nodes: %d   Edges: %d" % (len(vnodes), len(vedges)))
print("  Active configs now on canvas: %s" % live_names)
print("  Currently wired into 'LandIQ Config Agent': %s" % chosen_name)
print("  Backup: %s" % backup_path.name)
print("=" * 66 + "\n")
